### ISSUE TITLE
User Story 1 - List of Artworks

### ISSUE THREAD

**Issue by MonaHer** [MonaHer/capstone-mona#1]
## Value proposition

As an user
I want to see a list of all artworks
So that I can get an overview of all artworks

## Description

![Image](https://user-images.githubusercontent.com/132882726/251084229-20ba0bbd-76e7-4c62-aaf6-fdcd821c0243.png)

## Acceptance criteria

- [ ] All artworks from the data should be displayed as a list
- [ ] Each artwork should display an image

## Tasks

- [x] Create a branch
- [x] Fetch API with `SWR`
- [x] Create the component `Artworks` to render a list and pass it the `artworks` prop (data)
- [ ] Create the component `ArtworkPreview` and pass it the `image` and `id` props
