### ISSUE TITLE
User Story 7 - Starting page

### ISSUE THREAD

**Issue by MonaHer** [MonaHer/capstone-mona#12]
## Value proposition

As a user
I want to have a starting page, showing randomized artworks
So that I can see and get surprised by a diverse collection of artworks when I start the app

## Description

![Image](https://github.com/MonaHer/capstone-mona/assets/132882726/6874de61-1878-4e86-8c45-5ec4edda29e6)

## Acceptance criteria

- [ ] A starting page is displayed on the `index.js`
- [ ] The starting page shows randomized images, the name of the App and a loading animation
- [ ] The page changes to `pages/artworks-collection` after some seconds

## Tasks

- [x] Create a branch
- [ ] Restructure the pages of the app

**Comment by josch87** [comment]
I think your proposition is not logical yet. I guess that the mobile navigation is being displayed on every page. So the proposition would actually be for the mobile navigation, not for the homepage. What is the unique selling point for this page? Why do users really need it? Maybe to highlight the "note of the day" or the last entered note? Or a statistic about notes?
