### ISSUE TITLE
User Story 8 - Toggle function for Notes

### ISSUE THREAD

**Issue by MonaHer** [MonaHer/capstone-mona#15]
## Value proposition

As a user
I want to be able to fold and unfold my notes
So that I can have a structured and clear overview over my notes

## Description

![Image](https://user-images.githubusercontent.com/132882726/256230990-36070785-7a91-4125-9857-19dfcbb4ebd8.png)

## Acceptance criteria

- [ ] I can toggle what I see of my notes
- [ ] If my notes are folded, I can only see the title, if they are unfolded, I can see the title and the notes I wrote 

## Tasks

- [ ] Create a branch
- [ ] Create toggle function

**Comment by CorneliusMoe** [comment]
LGTM 🙌
