### ISSUE TITLE
User Story 9 - Favorite function

### ISSUE THREAD

**Issue by MonaHer** [MonaHer/capstone-mona#17]
## Value proposition

As a user
I want to mark artworks as favorites
So that I can find them easier

## Description

![Image](https://user-images.githubusercontent.com/132882726/256494138-b708755b-961e-4119-8d7d-f3af08cdb823.png)

## Acceptance criteria

- [ ] There's a small icon displayed on every artwork 
- [ ] If I click on the icon it will toggle from unfilled to filled
- [ ] If the icon is filled it means that this artwork is favored and the artwork will be displayed on `pages/favorites/index.js`
- [ ] If I toggle the icon to unfilled, it means that the artwork is not favored and it won't be displayed in the `pages/favorites/index.js` anymore

## Tasks

- [ ] Create a branch
- [ ] Create a `handleToggleFavorite` function
- [ ] Create a page `favorites/index.js`
- [ ] Create a `FavoriteButton` component
- [ ] Drill props

**Comment by Bilal4317** [comment]
lgtm
