### ISSUE TITLE
US 10 - Clean and restructure code

### ISSUE THREAD

**Issue by MonaHer** [MonaHer/capstone-mona#19]
## Value proposition

As a developer
I want to clean and restructure my code to improve its readability
So that I can make future changes and additions easier.

## Acceptance criteria

- [ ] Any unnecessary or redundant code is removed
- [ ] Consistent and meaningful naming conventions for variables, functions and styled components are applied
- [ ] All components have an `styles.js` for the styled components
- [ ] The code doesn't repeat itself

## Tasks

- [ ] Create a branch
- [ ] Identify and remove redundant code
- [ ] Check all names, if they are semantically correct
- [ ] Create `styles.js` for all components to structure the components more clean
