### ISSUE TITLE
User Story 2 - Artwork Information Page

### ISSUE THREAD

**Issue by MonaHer** [MonaHer/capstone-mona#2]
## Value proposition

As an user
I want to see the artwork with all information about it
So that I can learn everything about the artwork.

## Description

![Image](https://user-images.githubusercontent.com/132882726/251081830-9874eea9-04c0-4eea-b863-edec321bd255.png)

## Acceptance criteria

- [ ] Clicking an artwork from the `artworksList` shows all artworkInfos of the artwork
- [ ] The artwork's image is displayed
- [ ] The artwork's title is displayed
- [ ] The artwork's production period is displayed
- [ ] The artwork's creator is displayed
- [ ] The artwork's creator's life dates are displayed
- [ ] The artwork's dimensions are displayed
- [ ] The artwork's location in the museum is displayed
- [ ] The artwork's text is displayed
- [ ] Clicking on the "Next"-Button shows next page of artworks
- [ ] Clicking on the "Prev"-Button shows previous page of artworks

## Tasks

- [x] Create a branch
- [x] Create the component `ArtworkInfo`
- [x] Pass the props to the `ArtworkInfo` component
- [x] Create the page `pages/artworks/[id]`, that renders `ArtworkInfo`
- [x] Read the query parameter `id` from `next/router`
- [x] Use the `id` to find the artwork to display
