### ISSUE TITLE
User Story 3 - Notes function

### ISSUE THREAD

**Issue by MonaHer** [MonaHer/capstone-mona#3]
## Value proposition

As an user
I want to make notes about specific artworks
So that I can remember my thoughts and impressions about the artworks

## Description

![Image](https://user-images.githubusercontent.com/132882726/251169594-5df6ede8-b30b-4cb9-9d53-33d416c1c4ff.png)

## Acceptance criteria

- [ ] A text area is displayed under the information of every artwork
- [ ] The written text in the text area is automatically saved 
- [ ] The written text can be edited and deleted
- [ ] The size of the text area adjusts to fit the content.

## Tasks

- [x] Create a branch
- [x] Create a component component `Note`
- [x] Create a `useLocalStorageState`

**Comment by vaupunkt** [comment]
you could add where you want to save the note to. Is it an array with notes and the id of the picture that gets saved to local storage or how is the save-option structured? :)
