### ISSUE TITLE
User Story 4 - Search function

### ISSUE THREAD

**Issue by MonaHer** [MonaHer/capstone-mona#7]
## Value proposition

As a user
I want to search for artworks by the artwork's title or creator's name
So that I can find the artwork I want to take notes on more quickly

## Description

![Image](https://user-images.githubusercontent.com/132882726/252905074-dc16432f-e608-43a3-a509-d11159965d0c.png)

## Acceptance criteria

- [ ] A search field is displayed on `/search.index.js`
- [ ] A magnify icon and a placeholder text are displayed in the search field
- [ ] I can insert text into the search field
- [ ] When I type in the search field, only the artworks appear in the list below, of which the title or 
        creator's name match the typed text
- [ ] If I click on one image, I can see all information about the artwork
- [ ] The search term and the search results are saved in the local storage
- [ ] If the search has no match, a text "no results" is displayed below
- [ ] If I clear the search field, the search results disappear
- [ ] If I click on the link "Go to search" I get to `/search.index.js`, if I click "Go to ArtworkList" I get to `/index.js`

## Tasks

- [x] Create a branch
- [x] Create a component `searchBar`
- [x] Implement a search function to display only the artworks, that match the title or creator's name of the 
       typed text in the search field

**Comment by FelineHuhn** [comment]
Hey Mona, very nice user story 🎉 I love the wireframe. Maybe you could add one acceptance criteria, that mentions the loupe icon and displayed text inside the search field, to be more specific or? 

Also you could think about a little bit more suitable wording, instead of "result" and how the searching works, or? Maybe you could extend it something like: 

- When I type in the search field, only the artworks appear in the list below, of which the title or creator's name match the typed text
- If the search has no match, a text "no results" is displayed below 

Also in your task you don't point out the outcome of the search function. Maybe like: 
- Implement a search function to display only the artworks, that match the title or creator's name of the typed text in the search field

**Comment by DErdmann1** [comment]
Love it, Mona! :) Now your user story is nicely detailed and I think it’s ready to be worked on. I’m looking forward to testing your search function 👓
