### ISSUE TITLE
User Story 5 - Notebook

### ISSUE THREAD

**Issue by MonaHer** [MonaHer/capstone-mona#8]
## Value proposition

As a user
I want to see a list of all artworks, that I took notes on
So that I have a collection of all my notes

## Description

![Image](https://user-images.githubusercontent.com/132882726/252917061-5ed3a1dc-88dc-4697-9b36-7d4312c8cf9e.png)

## Acceptance criteria

- [ ] If I take notes on an artwork, the artwork inclusive the notes I made are displayed in a list on `pages/notebook.js`
- [ ] If I click one artwork in the list, I can see all information about the artwork and my notes
- [ ] If I have deleted my notes on one artwork, the artwork is not displayed on the `pages/notebook.js` anymore

## Tasks

- [x] Create a branch
- [x] Create a component `notesList` 
- [ ] Render `notesList` component on a new page `pages/notebook.js`
