### ISSUE TITLE
User Story 6 - Navigation

### ISSUE THREAD

**Issue by MonaHer** [MonaHer/capstone-mona#9]
## Value proposition

As a user
I want to be able to switch between the list of artworks and the notebook 
so that I can navigate the app easier.

## Description

![Image](https://github.com/MonaHer/capstone-mona/assets/132882726/c335a762-160c-46e4-9712-4730bb82bd0b)

## Acceptance criteria

- [ ] A navigation bar is displayed on every page
- [ ] Clicking "Artworks List" shows the `index.js`
- [ ] Clicking "My Notebook" shows the `pages/notebook.js`

## Tasks

- [x] Create a branch
- [x] Create a component `Navigation` that renders all navigation links

**Comment by ArnelaKapllani** [comment]
LGTM ❤️ @MonaHer
